drone: #namespace

    n_actions: 6 # 6 Ekintza, Aurrera, Atzera, Ezkerra, Eskubi

    linear_forward_speed: 0.5 # Speed for going fowards
    angular_turn_speed: 0.05 # Lineare speed when turning
    angular_speed: 0.3 # Angular speed when turning Left or Right

    init_linear_speed_vector:
      x: 0.0
      y: 0.0
      z: 0.0

    init_angular_turn_speed: 0.0 # Initial angular speed in shich we start each episode

    max_linear_aceleration: 5.0 # Linear acceleration value in

    min_sonar_value: 0.5 # Minimum meters below wich we consider we have crashed
    max_sonar_value: 5.0 # This can be retrieved form the sonar topic

    work_space: # 3D cube in which Drone is allowed to move
      x_max: 10.0
      x_min: -1.0
      y_max: 6.0
      y_min: -1.0
      z_max: 2.5
      z_min: 0.08

    max_roll: 1.57 # Max roll after which we end the episode
    max_pitch: 1.57 # Max roll after which we end the episode
    max_yaw: inf # Max yaw, its 4 because its bigger the pi, its a complete turn actually the maximum

    desired_pose:
      x: 9.0
      y: 4.0
      z: 2.0

    desired_point_epsilon: 1.0 # Error acceptable to consider that it has reached the desired point


    saria_gerturatu: 2  # Saria helmugara gerturatzeagatik
    saria_urrundu: -1  # Saria helmugatik hurruntzeagatik
    saria_muga_atera: -200 # Saria mugatik ateratzean
    episodioa_amaitu: 200 # Points given when ending an episode


