drone: #namespace
    task_and_robot_environment_name: 'ParrotDroneTaskJ-v0'
    ros_ws_abspath: "/home/josu/simulation_ws"
    #qlearn parameters
    alpha: 0.6
    gamma: 0.7
    epsilon: 0.9
    epsilon_discount: 0.999
    nepisodes: 120
    nsteps: 1000

