drone: #namespace

    n_actions: 4 # We have 4 actions, Up, Down, Forwards, Backwards, StrafeLeft, StrafeRight

    linear_forward_speed: 0.5 # Spwwed for ging fowards
    angular_turn_speed: 0.05 # Lienare speed when turning
    angular_speed: 0.3 # Angular speed when turning Left or Right

    init_linear_speed_vector:
      x: 0.0
      y: 0.0
      z: 0.0

    init_angular_turn_speed: 0.0 # Initial angular speed in shich we start each episode

    max_linear_aceleration: 5.0 # Linear acceleration value in

    min_sonar_value: 0.5 # Minimum meters below wich we consider we have crashed
    max_sonar_value: 5.0 # This can be retrieved form the sonar topic

    ibilbide_mugak: # 3D cube in which Drone is allowed to move
      x_max1: 8.5
      x_min1: -0.5
      y_max1: 0.5
      y_min1: -0.5
      z_max1: 2.0
      z_min1: 0.0
      x_max2: 8.5
      x_min2: 7.5
      y_max2: -1.0
      y_min2: 9.0
      z_max2: 3.0
      z_min2: 1.0
      x_max3: 9.0
      x_min3: -1.0
      y_max3: 9.0
      y_min3: 7.0
      z_max3: 3.0
      z_min3: 1.0



    max_roll: 1.57 # Max roll after which we end the episode
    max_pitch: 1.57 # Max roll after which we end the episode
    max_yaw: inf # Max yaw, its 4 because its bigger the pi, its a complete turn actually the maximum

    p1:
      x: 8.0
      y: 0.0
      z: 2.0

    p2:
      x: 8.0
      y: 8.0
      z: 2.0
    
    helmuga:
      x: 0.0
      y: 8.0
      z: 2.0

    desired_point_epsilon: 0.5 # Error acceptable to consider that it has reached the desired point

    pauso_eman: -1 # Pauso bat emateagatik saria
    gerturatu: 1 # Puntura gerturatzeagatik saria
    p1_iritsi: 50 # P1 iristagatik emandako saria
    p2_iritsi: 90 # P2 iristagatik emandako saria
    helmugara_iritsi: 200 # Helmugara iristagatik emandako saria
    ibilbidetik_atera: -200


