drone: #namespace
    task_and_robot_environment_name: 'DroneXYZ-v0'
    ros_ws_abspath: "/home/josu/simulation_ws"
    
    #qlearn parametroak
    alpha: 0.6
    gamma: 0.6
    epsilon: 0.99
    epsilon_discount: 0.9986
    nepisodes: 1200
    nsteps: 1200

